out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: CIFAR10
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CIFAR10
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: default
  layer_type: gatedgcnconv
  layers_mp: 4
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 45 
  batchnorm: False
  act: relu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
